"""Add Property Columns

Revision ID: bf84a906a218
Revises: 9a0a9a028d04
Create Date: 2024-03-07 14:13:04.824900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bf84a906a218'
down_revision: Union[str, None] = '9a0a9a028d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    action = postgresql.ENUM('rent', 'sell', 'lease', name='action')
    action.create(op.get_bind())
    op.add_column('properties', sa.Column('action', sa.Enum('rent', 'sell', 'lease', name='action'), nullable=True))
    op.add_column('properties', sa.Column('rent', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('num_rooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('properties', 'type')
    op.drop_column('properties', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('properties', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('properties', 'image_url')
    op.drop_column('properties', 'region')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'address')
    op.drop_column('properties', 'num_rooms')
    op.drop_column('properties', 'rent')
    op.drop_column('properties', 'action')
    action = postgresql.ENUM('rent', 'sell', 'lease', name='action')
    action.drop(op.get_bind())
    
    # ### end Alembic commands ###
